Improve docstrings for Gaussian beam sources to clarify the location of the waist
flexcompute/tidy3d pull request #1043
Opened 2023-07-31 17:53 UTC by shashwat-sh

2023-07-31 19:00 UTC, tylerflex approved these changes

2023-08-01 21:29 UTC, xin-flex requested changes
"behind" or "in front of" are still a bit ambiguous (what is the view point?). Is it possible to use words like "to the + direction of" instead?

2023-08-02 16:34 UTC, shashwat-sh commented
> "behind" or "in front of" are still a bit ambiguous (what is the view point?). Is it possible to use words like "to the + direction of" instead?

@xin-flex thanks, updated based on the comment

2023-08-03 13:09 UTC, shashwat-sh commented
Can I go ahead and merge this?

2023-08-03 13:10 UTC, merged