better error message when user try to download data that doesn't exist.
flexcompute/tidy3d pull request #1246
Opened 2023-11-11 12:02 UTC by magiWei

2023-11-13 14:25 UTC, tylerflex requested changes
Thanks @magiWei. Please also include a changing item under "fixed"
```
Improved error handling if file can not be downloaded from server.
```
Our practice is to include a changelog item for any non-trivial change to our code so we have a clear record of the timeline for various change. thank you!

2023-11-13 14:25 UTC, tylerflex commented on tidy3d/web/api/mode.py
> +                "Fail to download file from server. Please confirm if the task status = success."
Please change to
```
f"Failed to download file '{MODESOLVER_RESULT}' from server. Please confirm that the task was successful."
```

2023-11-13 14:25 UTC, tylerflex commented on tidy3d/web/core/task_core.py
> +                SIMULATION_DATA_HDF5,
Please change to
```
f"Failed to download file '{SIMULATION_DATA_HDF5}' from server. Please confirm that the task was successful."
```

2023-11-14 02:22 UTC, magiWei commented
> Thanks @magiWei. Please also include a changing item under "fixed"
> 
> ```
> Improved error handling if file can not be downloaded from server.
> ```
> 
> Our practice is to include a changelog item for any non-trivial change to our code so we have a clear record of the timeline for various change. thank you!

added.

2023-11-14 22:23 UTC, merged