Update the minimum tls version for python client to avoid https shake…
flexcompute/tidy3d pull request #1422
Opened 2024-01-30 06:01 UTC by magiWei

… verify issue.

2024-01-30 15:16 UTC, lei-flex requested changes

2024-01-30 15:17 UTC, lei-flex commented
@tylerflex @tomflexcompute could you also follow up to update the docs for this change, in Q&A part?

2024-01-31 01:13 UTC, magiWei commented on tidy3d/web/core/http_util.py
> +        self.reinit()
Good idea, a variable named `REINITIALIZED` is added to identify whether it has been reinited.

2024-02-01 16:51 UTC, lei-flex approved these changes
ship it.

2024-02-05 14:36 UTC, tylerflex commented
hi @magiWei after I merged the other PR, there are some merge conflicts here, could you fix them up and then I will take a last look and merge this, thanks!

2024-02-06 13:47 UTC, merged