Adding batch solving capability to the mode solver api
flexcompute/tidy3d pull request #1649
Opened 2024-04-29 22:05 UTC by prashkh

Made changes to tidy3d.plugis.mode.web.py and tidy3d.web.api.mode.py to add run_batch functionality

2024-04-30 13:48 UTC, tylerflex requested changes
Thanks @prashkh, this is looking pretty good already. Here are some initial comments to help clean up a few bits. Could you try to resolve them for the next commit with the local mode solve? Thank you!

2024-04-30 13:48 UTC, tylerflex commented on CHANGELOG.md
> +- A batch of Mode Solvers can be run concurrently using `tidy3d.plugins.mode.web.run_batch()`.
maybe "Mode Solvers" -> "`ModeSolver` objects"

2024-04-30 13:48 UTC, tylerflex commented on tidy3d/web/api/mode.py
> +            result = run(mode_solvers[index], f"{task_name}_{index}", f"mode_solver_batch_{index}", folder_name, results_files[index], False, progress_callback_upload, progress_callback_download)
could you call this `run` with keyword arguments (eg `task_name=f"{task_name}_{index}"`)? it just helps keep things a bit easier to read and also helps avoids bugs if the arguments change positions later.

2024-04-30 13:48 UTC, tylerflex commented on pyproject.toml
seems like something went a bit awry with the rebase in that some of the changes seem to be applied to 2.6.3. Could you make sure you have the most up to date `pre/2.7` and try again? Ideally there should just be one commit in the PR and none of these extra changes. Sometimes it takes a little trial and error to get right.

2024-04-30 13:48 UTC, tylerflex commented on tidy3d/web/api/mode.py
> +    retry_delay: int = DEFAULT_RETRY_DELAY,
probably this is a `float`?

2024-04-30 13:48 UTC, tylerflex commented on tidy3d/web/api/mode.py
> +        A list of ModeSolverData objects containing the results from each simulation in the batch. None is placed in the list for simulations that fail after all retries.
make sure `None` is in double backslash quotes

2024-04-30 13:48 UTC, tylerflex commented on tidy3d/web/api/mode.py
> +        console.print("[red]ERROR: Stopped running a batch of mode solver simulations. Please provide a list of mode solvers of type [cyan]`td.plugins.mode.mode_solver.ModeSolver` [red]to run a batch
I think we're using `console.log` in the rest of the code.

Also, for messages like this going to STDOUT, we want to put the variables in regular single quotes `'`. not backslash quotes. It's a bit confusing..

2024-04-30 13:48 UTC, tylerflex commented on tidy3d/web/api/mode.py
> +    if False in [type(x)== ModeSolver for x in mode_solvers]:
maybe a bit standard to do
```
if not all(isinstance(x, ModeSolver) for x in mode_solvers):
```

2024-04-30 13:48 UTC, tylerflex commented on tidy3d/web/api/mode.py
> +        console.print("[red]ERROR: Stopped running a batch of mode solver simulations. Please provide a list of mode solvers of type [cyan]`td.plugins.mode.mode_solver.ModeSolver` [red]to run a batch
Also probably makes more sense to simply `raise ValueError(...)` here.

2024-04-30 13:48 UTC, tylerflex commented on tidy3d/web/api/mode.py
> +    def handle_simulation(index, retries=0):
can you put the comment as a docstring? 

```py
def handle_simulation(...):
    """Handling simulation to make sure there are more than one tries if simulation produces some error"""
```
and also add type information for the arguments and return?

2024-04-30 13:48 UTC, tylerflex commented on tidy3d/web/api/mode.py
> +        futures = [executor.submit(handle_simulation, i) for i in range(len(mode_solvers))]
`len(mode_solvers)` gets used a lot, maybe just define a `num_mode_solvers = len(mode_solvers)` variable somewhere?

2024-04-30 13:48 UTC, tylerflex commented on tidy3d/web/api/mode.py
> +                pbar_message = f"[cyan]Running a batch of [deep_pink4]{len(mode_solvers)} mode solvers [cyan]in parallel.\n"
some purists might take issue with "in parallel" and could email us for clarification. Maybe we should just leave this part out and just saying that we're running a batch of {N} mode solvers should be enough

2024-04-30 13:48 UTC, tylerflex commented on tidy3d/web/api/mode.py
> +                results[index] = None
`results[index]` is already initialized as `None` right? so maybe we just `return`? Also, should we `log.warning()` that  the `index`-th mode solver failed?

2024-04-30 13:48 UTC, tylerflex commented on tidy3d/web/api/mode.py
> +                        console.print(f"[red]A ModeSolver task has timed out.")
Just wondering, when does this get triggered? eg. if there's a connection error? how long do we wait? Maybe can you explain what this is catching? is it different from the retry code in `handle_simulation`?

Please put `ModeSolver` in single quotes `'` for terminal output. 

Also let's use `console.log()` for consistency

is there any way to get the index of this mode solver in the original list for display?

2024-04-30 13:48 UTC, tylerflex commented on tidy3d/web/api/mode.py
> +    def handle_simulation(index, retries=0):
Should we call this `handle_mode_solver`? not `simulation`? More generally, it seems `simulation` sneaks in the comments and stuff, just checking.

2024-04-30 13:48 UTC, tylerflex commented on tidy3d/web/api/mode.py
> +                console.print("[green]Batch simulations completed successfully!")
batch of 'ModeSolver's maybe?

Also, how do we handle this if one of them actually failed? does the progress bar get completed still and do we still print this message?

2024-05-01 18:07 UTC, tylerflex commented
@prashkh should we close this in favor of #1654?

2024-05-01 18:09 UTC, prashkh commented
@tylerflex Yes, let's close this one and continue it on #1654

2024-05-01 18:09 UTC, closed without merging