Adding num_proc arg to adjoint run_local, and properly avoiding validators
flexcompute/tidy3d pull request #1686
Opened 2024-05-07 20:46 UTC by momchil-flex

2024-05-07 23:34 UTC, tylerflex requested changes
Couple minor things but overall looks good. Think it requires a changelog fixed item?

2024-05-07 23:34 UTC, tylerflex commented on tests/test_plugins/test_adjoint.py
> +
let's throw in a test asserting that AdjointError is raised if `grad ` is called on a function where `run` is used? for good measure? unless this seems unnecessary

2024-05-07 23:34 UTC, tylerflex commented on tidy3d/plugins/adjoint/web.py
> +    num_proc: int = 1,
let's use the default defined in `simulation.py` `NUM_PROC_LOCAL` here

2024-05-08 12:29 UTC, tylerflex approved these changes
looks good, will leave it up to you regarding changelog. maybe since the skipped validators were introduced in 2.7 rc1 (I think?) we can just leave it out as it will be fixed in 2.7

2024-05-08 12:33 UTC, tylerflex commented
@prashkh It seems like on python3.9, all the results are `None`. Would you mind looking into this? Im not really sure how to proceed. Perhaps there is some error that is getting caught by the `try/except`?

2024-05-08 12:33 UTC, tylerflex commented
it's possible when I tried to recover your changes, I missed some detail?

2024-05-08 12:40 UTC, prashkh commented
@tylerflex This PR is for the test_adjoing or are you still talking about run_batch addition for the web mode solver?

2024-05-08 12:49 UTC, tylerflex commented
Yea sorry, wrong PR.. supposed to be commenting on this one #1685 :D

2024-05-13 14:40 UTC, merged