add the num_freqs arg to .to_source methods
flexcompute/tidy3d pull request #1935
Opened 2024-08-30 14:35 UTC by FilipeFcp

Hi @tylerflex.
I am opening the PR to fix #1926.

I just added the `num_freqs` argument to the `.to_source` method for the `ModeSolve` and `ComponentModeler`.
I added it with the default value of 1.

I added only you as a reviewer only because it seems quite simple.

Thank you

2024-08-30 15:46 UTC, tylerflex commented
Looks great, thanks @FilipeFcp ! 

could you also add a single line under the changelog "fixed" in Unreleased? describing the fix?

Also adding @caseyflex just so he's aware and whether he sees any potential conflicts with the new mode solver

2024-08-30 15:47 UTC, tylerflex commented
@FilipeFcp after you add a commit with the changelog edits, you can try using `git rebase` to squash these into a single commit, which helps keep the history more clear.  Will be a good thing to learn as we use it all the time. There's an explanation here

https://www.notion.so/flexcompute/Git-Rebasing-6a7b343ee1cf4ca28fdad0a870354eee#3401e891b41447e3a1defd84c19023cb

2024-08-30 16:03 UTC, FilipeFcp commented
Thanks, @tylerflex! I have read that, but I thought that since there is only a single commit, there would be nothing to squash. Is there something I might be missing?

2024-08-30 16:48 UTC, tylerflex commented
If you add the change to the changelog , it will add another commit to this PR

2024-08-30 17:22 UTC, FilipeFcp commented
@tylerflex Of course, thanks for clarifying! Done.

2024-08-30 19:04 UTC, tylerflex requested changes
Looks good, thanks @FilipeFcp , just a comment about an extra `_` in the changelog.

2024-08-30 19:04 UTC, tylerflex commented on CHANGELOG.md
> +- Added the option to specify the `num_freqs` argument to the `._to_source` method for both `ModeSolver` and `ComponentModeler`.
please remove underscore `_` in `_to_source`

2024-08-30 19:38 UTC, tylerflex approved these changes
Thanks @FilipeFcp !

2024-08-30 19:50 UTC, FilipeFcp commented
Thank you @tylerflex and @daquinteroflex, for reviewing and taking the time to help me with the workflow.

2024-08-30 20:05 UTC, tylerflex commented
quick study :D

2024-09-03 08:10 UTC, caseyflex approved these changes
Thanks for the heads up! Looks good. I guess we could also generally support passing kwargs for this kind of method, but it's good to highlight individual arguments that may be of interest.

I will have to be rather careful about conflicts until my ModeSimulation PR is merged -- it seems like it could be easy to accidentally lose changes made to the ModeSolver plugin, since my PR moves everything to components. I'll have to manually move over every change made to the ModeSolver in the interim.

2024-09-03 15:25 UTC, tylerflex commented
Hi @FilipeFcp looks like the changelog got out of date with `develop`, so could you do one last rebase here (against the updated version of develop, eg after performing a git pull origin develop)? And if you're inclined, you could add **kwargs to the method signatures and pass these `**kwargs` in along with the `num_freqs`.

Then this should be good to merge (which I'll take care of)

Thanks

2024-09-04 01:29 UTC, FilipeFcp commented
I think is all set @tylerflex. Thanks!

2024-09-04 12:04 UTC, merged