Show WebAPI system warning message.
flexcompute/tidy3d pull request #2075
Opened 2024-11-18 06:22 UTC by magiWei

2024-11-18 08:09 UTC, magiWei commented
@tylerflex @momchil-flex This requirement is from Emerson: https://flow360.atlassian.net/browse/SCEM-8018

2024-11-18 14:12 UTC, tylerflex commented on tidy3d/web/core/log.py
this is just copied directly from `tidy3d/log.py`?  I think this is not a good idea since we will need to maintain two identical files. is there a better approach?

2024-11-19 01:05 UTC, QingengWei commented on tidy3d/web/core/log.py
Maybe we can move  tidy3d/log.py  to tidy3d/core/log.py.

2024-11-19 13:15 UTC, tylerflex commented on tidy3d/web/core/log.py
The problem with this is that the log is used internally in the tidy3d components. So if we move it to `web` then we would be forced to import `web` (and do authentication and other things) to use `tidy3d`. It wold be nice if they were separate. What about just using the rich console to do the logging here? like we do in `web.monitor`?

2024-11-19 13:32 UTC, momchil-flex commented on tidy3d/web/core/log.py
I am actually confused, why is this a problem? `tidy3d/log.py` is top level for both the `components` and `web` modules, why can't both just import it?

2024-11-20 04:34 UTC, magiWei commented on tidy3d/web/core/log.py
According to the original agreement, web/core is the bottom layer and cannot depend on other components, otherwise it will cause circular dependencies.

2024-11-20 04:34 UTC, magiWei commented on tidy3d/web/core/log.py
> The problem with this is that the log is used internally in the tidy3d components. So if we move it to `web` then we would be forced to import `web` (and do authentication and other things) to use `tidy3d`. It wold be nice if they were separate. What about just using the rich console to do the logging here? like we do in `web.monitor`?

I think a rich console is a good idea. It just be used in tidy3d/core

2024-11-20 09:02 UTC, momchil-flex commented on tidy3d/web/core/log.py
> According to the original agreement, web/core is the bottom layer and cannot depend on other components, otherwise it will cause circular dependencies.

I see, but is this really a problem for the log or rather specifically for things in `components/` and `plugins/`. I could see logic behind things we put in the main `tidy3d` folder to be usable by all other modules, i.e. both components and web. @tylerflex ?

2024-11-20 15:05 UTC, tylerflex commented on tidy3d/web/core/log.py
The way it was designed, the web API and tidy3d could be agnostic of one another. And just communicate through this "stub" class. In principle I think we could import log into web/core, but for now I'd prefer using rich console to not break this architecture unless we really need to. In the future we can figure out a better long term solution to decouple these things. probably the web API needs to be its own package and it might just need to import tidy3d as a dependency.

2024-11-20 15:14 UTC, momchil-flex commented on tidy3d/web/core/log.py
Ok, now I see, I think then to me it sounds like this warning should ideally be propagated from `web/core` to the corresponding `web/api` function where it occurs, and just shown there using the usual log. But for the time being rich console sounds good.

2024-11-21 01:31 UTC, magiWei commented on tidy3d/web/core/log.py
Ok, I have changed to rich console.

2024-11-21 01:35 UTC, magiWei commented on tidy3d/web/core/log.py
> The way it was designed, the web API and tidy3d could be agnostic of one another. And just communicate through this "stub" class. In principle I think we could import log into web/core, but for now I'd prefer using rich console to not break this architecture unless we really need to. In the future we can figure out a better long term solution to decouple these things. probably the web API needs to be its own package and it might just need to import tidy3d as a dependency.

Good idea, We should not embed web/* into tidy3d, because some users will not use web functions. We need to make web/* an independent package and then depend on tidy3d. In this way, users can choose the appropriate package to use based on their needs.

2024-11-21 14:00 UTC, tylerflex requested changes
Hi @magiWei Looks good overall but see how we do the logger in other parts of web/core

https://github.com/flexcompute/tidy3d/blob/develop/tidy3d/web/core/environment.py#L93-L106

let's use this `get_logger()` for consistency and so we can change the base config and have it reflect everywhere. 

Also wonder if momchil's suggestion about just handing the warning in the `web/api` side makes some sense? but for now maybe this is sufficient
Thanks

2024-11-21 14:08 UTC, magiWei commented
> Hi @magiWei Looks good overall but see how we do the logger in other parts of web/core
> 
> https://github.com/flexcompute/tidy3d/blob/develop/tidy3d/web/core/environment.py#L93-L106
> 
> let's use this `get_logger()` for consistency and so we can change the base config and have it reflect everywhere.
> 
> Also wonder if momchil's suggestion about just handing the warning in the `web/api` side makes some sense? but for now maybe this is sufficient Thanks

Ok, it makes sense to me. Changed.

2024-11-21 15:18 UTC, tylerflex approved these changes

2024-11-25 13:33 UTC, merged