Suggest a better f_width for TerminalComponentModeler
flexcompute/tidy3d pull request #2086
Opened 2024-11-21 21:59 UTC by QimingFlex

Previous parameters result a central frequency out of the frequency range as shown on the left, which uses f_min=0 and f_max = 50GHz. I took f_width=0.5*freq_0, which might not be optimal but helps centre the frequency at around 25GHz and improved S-parameters a bit.
![image](https://github.com/user-attachments/assets/3a42b384-a3af-47cc-9b47-e60d28e23889)
![Screenshot from 2024-11-21 16-58-17](https://github.com/user-attachments/assets/6835e7d3-e032-4c4e-9e05-44ff9bbbdd00)

2024-11-21 22:02 UTC, QimingFlex commented
![Screenshot from 2024-11-21 16-01-36](https://github.com/user-attachments/assets/f2dde15e-fd14-41b7-b2cc-47cf4f2d5dd6)
![Screenshot from 2024-11-21 17-02-09](https://github.com/user-attachments/assets/6b917a12-e786-476b-91f3-2712ff7c578c)

2024-11-22 17:18 UTC, weiliangjin2021 commented
How about the case where `freqs` is not uniformly distributed: say freq0 is almost f_min, the new approach will result in too narrow bandwidth?

2024-11-22 17:32 UTC, dmarek-flex commented
@QimingFlex Can you also try the old way for choosing bandwidth, but use a smaller `shutoff` for the simulation. Simply using a smaller `shutoff` might remove those ripples as well.

2024-11-25 17:09 UTC, QimingFlex commented
> How about the case where `freqs` is not uniformly distributed: say freq0 is almost f_min, the new approach will result in too narrow bandwidth?

Good point! I guess just averaging and minimum and maximum by `freq0 = (min(self.freqs) + max(self.freqs)) / 2` will work?

2024-11-25 17:12 UTC, QimingFlex commented
> @QimingFlex Can you also try the old way for choosing bandwidth, but use a smaller `shutoff` for the simulation. Simply using a smaller `shutoff` might remove those ripples as well.

![Screenshot from 2024-11-25 10-13-09](https://github.com/user-attachments/assets/ea6b1885-1cd0-42f5-865f-7213191a85bc)
![image (2)](https://github.com/user-attachments/assets/3338445e-bae3-4959-b557-932e58cea15a)

Yes, it has indeed improved. These two figures show the original f_width and the updated f_width, both with a smaller shutoff factor.

2024-11-25 17:22 UTC, weiliangjin2021 commented
> > How about the case where `freqs` is not uniformly distributed: say freq0 is almost f_min, the new approach will result in too narrow bandwidth?
> 
> Good point! I guess just averaging and minimum and maximum by `freq0 = (min(self.freqs) + max(self.freqs)) / 2` will work?

Sounds good. No edge cases come to my mind so far.

2024-11-25 17:39 UTC, dmarek-flex commented
> Yes, it has indeed improved. These two figures show the original f_width and the updated f_width, both with a smaller shutoff factor.

Great, so using the new `f_width` is definitely an improvement.

2024-11-27 14:40 UTC, dmarek-flex requested changes
Also should update the changelog

2024-11-27 14:40 UTC, dmarek-flex commented on tidy3d/plugins/smatrix/component_modelers/terminal.py
> +        fwidth = freq0 * np.sqrt(2) / np.pi
This should be better in most cases in RF applications. However, what if the user wants a simulation, which truly has a lower bound on the minimum frequency? This `fwidth` is based only on the central frequency.

It seems like the ripple issue was because the bandwidth was larger than needed and lower frequencies had higher amplitudes. Why not use the `fdiff` calculation from the previous commit, but scale it appropriately so that the amplitude of the min and max frequency is set to some desired value, such as 0.1.

2025-01-03 15:50 UTC, momchil-flex commented
What's the status here, can we move it forward?

2025-01-03 16:02 UTC, QimingFlex commented on tidy3d/plugins/smatrix/component_modelers/terminal.py
> +        fwidth = freq0 * np.sqrt(2) / np.pi
Sorry, could you clarify what you mean by lower bound on the minimum frequency? I think fwidth can be determined by `freq0` alone to ensure a symmetrical spectrum and the desired levels at both min and max. It seems like `fdiff` might not be needed.

2025-01-03 16:18 UTC, QimingFlex commented
> What's the status here, can we move it forward?

Will complete by today.

2025-01-03 16:35 UTC, dmarek-flex commented on tidy3d/plugins/smatrix/component_modelers/terminal.py
> +        fwidth = freq0 * np.sqrt(2) / np.pi
Let's say the minimum frequency the user chooses is much larger than 0. There might be good reason for this, e.g., less padding needed for PML or maybe avoiding a resonance at lower frequencies. With this approach, changing the min frequency does not affect the bandwidth that much. As the min frequency approaches the max frequency, the signal bandwidth should drop, probably up to some minimum value ideally.

Basically using this new approach, the user cannot specify the frequency bandwidth of the input signal independent of the central frequency. 

I also realized that your comment does not seem correct for the amplitude of the maximum frequency. If you keep the max frequency the same but change the min frequency, the power spectral density of the signal at the max frequency will change, right?

I think a better approach is to calculate `freq0` as you proposed, but modify the `fwidth` calculation, so that it uses the min and max frequency to ensure some desired power spectral density at those frequencies, perhaps the value of 0.1 in your comment or 0.01 if it represents power.

2025-01-03 16:39 UTC, dmarek-flex commented on tidy3d/plugins/smatrix/component_modelers/terminal.py
> +        fwidth = freq0 * np.sqrt(2) / np.pi
I think the main issue causing ripples in the S parameters was that the bandwidth was simply too large for the central frequency. But the original general idea of calculating `fdiff` using the min and max frequency was ok, maybe just needs to be scaled differently.

2025-01-03 16:43 UTC, QimingFlex commented on tidy3d/plugins/smatrix/component_modelers/terminal.py
> +        fwidth = freq0 * np.sqrt(2) / np.pi
Ah, you are right! We need a smaller scale for `fdiff` then.

2025-01-03 21:41 UTC, QimingFlex commented
> What's the status here, can we move it forward?

@dmarek-flex @momchil-flex After a thorough investigation, I found that the main reason for the discrepancy in S-parameters is the voltage integral path. The current Gaussian source works properly, so for now, we don't need to make any changes. I will close this PR :).

2025-01-03 21:41 UTC, closed without merging

2025-01-03 21:43 UTC, weiliangjin2021 commented
> > What's the status here, can we move it forward?
> 
> @dmarek-flex @momchil-flex After a thorough investigation, I found that the main reason for the discrepancy in S-parameters is the voltage integral path. The current Gaussian source works properly, so for now, we don't need to make any changes. I will close this PR :).

You showed several figures in this PR, which seems to be related to fwidth?

2025-01-03 22:01 UTC, QimingFlex commented
> > > What's the status here, can we move it forward?
> > 
> > 
> > @dmarek-flex @momchil-flex After a thorough investigation, I found that the main reason for the discrepancy in S-parameters is the voltage integral path. The current Gaussian source works properly, so for now, we don't need to make any changes. I will close this PR :).
> 
> You showed several figures in this PR, which seems to be related to fwidth?

Yeah, but it seems that several factors, including the integral path, PMLs, mesh, and pulse, collectively contribute to the ripples in the S-parameters. Previously, I wasn't able to ensure the integral path, PMLs, and mesh were idealy set up. Now, with those optimized, the current pulse produces nice S-parameters as shown.
![image](https://github.com/user-attachments/assets/d39caea4-3861-486b-8612-d74bad98063a)
![Screenshot from 2025-01-03 16-59-47](https://github.com/user-attachments/assets/5996bac2-b7a8-4f0b-8800-4e4a80efacd8)

2025-01-03 22:11 UTC, weiliangjin2021 commented
> Yeah, but it seems that several factors, including the integral path, PMLs, mesh, and pulse, collectively contribute to the ripples in the S-parameters. Previously, I wasn't able to ensure the integral path, PMLs, and mesh were idealy set up. Now, with those optimized, the current pulse produces nice S-parameters as shown.

That's good to know! Has the optimized integral path/PMLs/mesh been wrapped in a PR?

2025-01-03 23:01 UTC, QimingFlex commented
> > Yeah, but it seems that several factors, including the integral path, PMLs, mesh, and pulse, collectively contribute to the ripples in the S-parameters. Previously, I wasn't able to ensure the integral path, PMLs, and mesh were idealy set up. Now, with those optimized, the current pulse produces nice S-parameters as shown.
> 
> That's good to know! Has the optimized integral path/PMLs/mesh been wrapped in a PR?

PMLs simply need more layers (>50), and the mesh should better be uniform along the propagation direction. Could these be demonstrated in an example notebook for users? The tricky part is the integral path, and the voltage integral path plays a more important role in the S-parameters. The best path is to align the integral path along the grid line at the center of the copper thickness. 
/home/flexqiming/Pictures/Screenshots/Screenshot from 2025-01-03 17-52-07.png

2025-01-06 13:34 UTC, momchil-flex commented
> PMLs simply need more layers (>50)

I'm still a bit curious about this, wondering what causes it. The only cases I can think of so far where increasing the number of pml layers helps is simulations with periodic or Bloch boundaries in 2 dimensions and PML on the other, where oblique waves would not be well absorbed. This shouldn't be the case here though because there's PML in all 3 directions. But maybe somehow if one does a Fourier transform of the propagating mode in the plane parallel to the PML, there would be strong components close to oblique incidence? I really want to understand what exactly is causing this problem to require more PML layers, so we can make a more general recommendation for the users.

2025-01-06 16:00 UTC, dmarek-flex commented
> The best path is to align the integral path along the grid line at the center of the copper thickness.

That is an interesting observation, so in the inaccurate version of the results there was only a single cell to cover the metal thickness? As a result, the path would be snapped to the top or bottom boundary of that cell?

2025-01-07 16:15 UTC, QimingFlex commented
Yes, it seems there are edge effects around the PEC edges, which result in an inaccurate integral.

2025-01-07 16:16 UTC, QimingFlex commented
> > The best path is to align the integral path along the grid line at the center of the copper thickness.
> 
> That is an interesting observation, so in the inaccurate version of the results there was only a single cell to cover the metal thickness? As a result, the path would be snapped to the top or bottom boundary of that cell?

Yes, it seems there are edge effects around the PEC edges, which result in an inaccurate integral.

2025-01-07 22:46 UTC, QimingFlex commented
> > PMLs simply need more layers (>50)
> 
> I'm still a bit curious about this, wondering what causes it. The only cases I can think of so far where increasing the number of pml layers helps is simulations with periodic or Bloch boundaries in 2 dimensions and PML on the other, where oblique waves would not be well absorbed. This shouldn't be the case here though because there's PML in all 3 directions. But maybe somehow if one does a Fourier transform of the propagating mode in the plane parallel to the PML, there would be strong components close to oblique incidence? I really want to understand what exactly is causing this problem to require more PML layers, so we can make a more general recommendation for the users.

After conducting more tests, I conclude that the voltage integral path largely suppresses all other factors affecting the accuracy of S-parameters. Now, if the voltage integral path is chosen correctly, using a PML with 12 layers produces excellent results. But there is one issue with the PML: since it does not absorb the DC component, we use `remove_DC_component=True`, which causes an abrupt jump at low frequencies in S-parameters or other post-processing results. Although our main focus is on the high-frequency range, it would be better to smooth out the low frequencies. Any ideas on how to achieve this?

![image](https://github.com/user-attachments/assets/adf65667-9402-48fc-b0d2-e08ec25527eb)

2025-01-08 12:36 UTC, momchil-flex commented
> But there is one issue with the PML: since it does not absorb the DC component, we use remove_DC_component=True, which causes an abrupt jump at low frequencies in S-parameters or other post-processing results.

Sorry, are the results bad if you do not remove the DC component? When I tested your notebook a little, what I noticed was that the fields never fully decay because of the DC part, but apart from that results looked the same?

In your plot, is the error / sharp jump due to the fact that there's very very little power at such low frequencies when DC component is removed? Or how should I understand it?