Added polarized far field components to DirectivityData
flexcompute/tidy3d pull request #2129
Opened 2024-12-17 23:28 UTC by QimingFlex

2024-12-18 13:41 UTC, momchil-flex commented
Does it make more sense to store the linearly polarized fields and add properties to get the circularly polarized ones?

2024-12-18 14:59 UTC, QimingFlex commented
> Does it make more sense to store the linearly polarized fields and add properties to get the circularly polarized ones?

Linearly polarized fields are the regular far-field components Etheta​ and Ephi​. I was previously thinking of putting E_left and E_right as properties of FarfieldProjectionMonitor, but doing so would require users to define both FarfieldProjectionMonitor and DirectivityMonitor to obtain all radiation characteristics. So I placed E_left​ and E_right​ under DirectivityMonitor, allowing users to access these radiation characteristics with just one monitor. Maybe a better way is to keep all six far-field components (Er to Hphi​) as fields in DirectivityData and introduce E_left​ and E_right as properties?

2024-12-18 15:14 UTC, dmarek-flex commented
> Does it make more sense to store the linearly polarized fields and add properties to get the circularly polarized ones?

I agree. For simplicity and extensibility, I think the `DirectivityData` should only store Etheta/Ephi far fields and total flux. Most antenna characteristics of interest can be derived from that data. We should not even need the radial components in the far field. (We could also compute H far fields on-the-fly given the background medium, but maybe simpler to keep it the way it is and store it explicitly.)

@QimingFlex can you think of any parameters of interest where the far field approximation is not used for antennas?

2024-12-19 22:43 UTC, QimingFlex commented
> > Does it make more sense to store the linearly polarized fields and add properties to get the circularly polarized ones?
> 
> I agree. For simplicity and extensibility, I think the `DirectivityData` should only store Etheta/Ephi far fields and total flux. Most antenna characteristics of interest can be derived from that data. We should not even need the radial components in the far field. (We could also compute H far fields on-the-fly given the background medium, but maybe simpler to keep it the way it is and store it explicitly.)
> 
> @QimingFlex can you think of any parameters of interest where the far field approximation is not used for antennas?

This sounds like a good plan. We store DirectivityData only with Etheta/Ephi, Htheta/Hphi, and total flux. Other characteristics, such as directivity, axial ratio, and polarized fields, are defined as properties. How do you think? @weiliangjin2021

2024-12-20 01:11 UTC, weiliangjin2021 commented
> This sounds like a good plan. We store DirectivityData only with Etheta/Ephi, Htheta/Hphi, and total flux. Other characteristics, such as directivity, axial ratio, and polarized fields, are defined as properties. How do you think?

Sounds good to me.

2024-12-21 09:26 UTC, momchil-flex commented
Sorry, wouldn't this now be almost identical to a far field monitor? Should we consider unifying, e.g. deprectating DirectivityMonitor, and adding the directivity, axial ratio, etc. properties to the FarFieldAngleMonitor?

2024-12-21 15:06 UTC, QimingFlex commented
> Sorry, wouldn't this now be almost identical to a far field monitor? Should we consider unifying, e.g. deprectating DirectivityMonitor, and adding the directivity, axial ratio, etc. properties to the FarFieldAngleMonitor?

The difference lies in DirectivityMonitor inheriting FluxMonitor to compute directivity. Do you think it would be better for FarFieldAngleMonitor to inherit FluxMonitor and store flux as a field in FarFieldAngleData? This will allow DirectivitiMonitor to be depracted.

2024-12-23 13:00 UTC, momchil-flex commented
Ok, I think it makes sense as is.

Note that you're modifying the notebooks submodule.

2024-12-23 20:49 UTC, dmarek-flex requested changes
Great, this looks a lot simpler @QimingFlex! Couple of simple things and yea just need to revert the notebooks module.

2024-12-23 20:49 UTC, dmarek-flex commented on CHANGELOG.md
> +- Polarized far field components to `DirectivityData`.
suggestion: `- DirectivityMonitor can now be used to decompose fields into circular polarization states.`

2024-12-23 20:49 UTC, dmarek-flex commented on CHANGELOG.md
> +- Refactored `DirectivityData` fields: Now stores only far fields and flux. Radiation characteristics (e.g., directivity, axial ratio) are computed through properties.
Again I would suggest focusing on how the `DirectivityMonitor` has been changed. For example: The behavior of the `DirectivityMonitor` was changed, so that only far fields and flux are stored. Other radiation characteristics ...

2024-12-23 20:49 UTC, dmarek-flex commented on tidy3d/components/data/monitor_data.py
> +    def left_polarization(self):
`left_hand_polarization`
in the comments add parenthetically that it is the counter clockwise component of circular polarization

same for the other polarization

2024-12-23 20:49 UTC, dmarek-flex commented on tests/test_data/test_monitor_data.py
> +    data = make_far_field_data_array()
modify test to include the new fields `left_polarization` and `right_polarization`.

2024-12-23 20:49 UTC, dmarek-flex commented on tidy3d/components/data/monitor_data.py
> +        ..., title="Flux", description="Flux values in the frequency-domain."
dont need a hyphen in "frequency-domain" for this case

2025-01-02 14:20 UTC, QimingFlex commented on tests/test_data/test_monitor_data.py
> +    data = make_far_field_data_array()
`left_polarization` and `right_polarization` are properties now rather than fields.

2025-01-03 22:34 UTC, weiliangjin2021 commented on CHANGELOG.md
> +- Refactored `DirectivityData` fields: Now stores only far fields and flux. Radiation characteristics (e.g., directivity, axial ratio) are computed through properties.
Missing "are stored" in the revised version.

2025-01-03 23:04 UTC, weiliangjin2021 commented on CHANGELOG.md
> +- The behavior of `DirectivityData` was changed, so that only far fields and flux are stored. Radiation characteristics (e.g., directivity, axial ratio) are computed through properties.
"are computed" --> "can be accessed"

2025-01-03 23:04 UTC, weiliangjin2021 commented on tidy3d/components/data/monitor_data.py
> +    >>> complex_values = (1+1j) * np.random.random((len(r), len(theta), len(phi), len(f)))
Please update the example code here. Line 2041 seem outdated.

2025-01-03 23:04 UTC, weiliangjin2021 commented on tidy3d/components/data/monitor_data.py
> +    def directivity(self):
return signature `->float`. The same for other properties

2025-01-03 23:04 UTC, weiliangjin2021 commented on tidy3d/components/data/monitor_data.py
> +        Note
I believe "Note" only works appropriately if you have a blank line above "Note"

2025-01-03 23:04 UTC, weiliangjin2021 commented on tidy3d/components/data/monitor_data.py
> +        "Left polarization (counter clockwise component of circular polarization) electric far field with an angle-based projection grid."
The line here looks super long. Better to split the line. The same to the next property.

2025-01-03 23:04 UTC, weiliangjin2021 commented on tidy3d/components/data/monitor_data.py
> +        "Left polarization (counter clockwise component of circular polarization) electric far field with an angle-based projection grid."
Also please improve the sentence a bit. E.g. "counterclockwise"; "Left polarized far field component of electric field..."

2025-01-03 23:06 UTC, weiliangjin2021 reviewed
Could you also add tests for left and right polarization?

2025-01-03 23:28 UTC, QimingFlex commented on tidy3d/components/data/monitor_data.py
> +    def directivity(self):
would it be better to use `DataArray`?

2025-01-03 23:32 UTC, weiliangjin2021 commented on tidy3d/components/data/monitor_data.py
> +    def directivity(self):
ah sorry, it's DataArray

2025-01-04 01:32 UTC, weiliangjin2021 approved these changes
Approve once tests for right/left polarization have been added

2025-01-06 15:55 UTC, dmarek-flex commented on tests/test_data/test_monitor_data.py
> +    data = make_far_field_data_array()
True, but make sure those properties are tested in `test_directivity_data():`

2025-01-06 15:57 UTC, dmarek-flex approved these changes
Looks great, approved! but yeah please add testing of the new properties

2025-01-07 21:19 UTC, merged