webapi fixes
flexcompute/tidy3d pull request #277
Opened 2022-03-29 18:05 UTC by momchil-flex

Credential folder only created when needed
Maximum attempts in authentication while loops
Authentication only called when needed, and checks if already done

2022-03-29 18:12 UTC, tylerflex requested changes

2022-03-29 18:12 UTC, tylerflex commented on tidy3d/web/auth.py
> +    If Config["auth" is already set, returns immediately.
typo

2022-03-29 18:12 UTC, tylerflex commented on tidy3d/web/auth.py
> +    def auth_before_call(*args, **kwargs):
add a functools.wraps here to copy the docstring info over

2022-03-29 18:14 UTC, tylerflex commented
So what is the new behavior of this in terms of users?  Will it try to log in each web api call?  

Also, does this print anything to STDOUT each auth call because that could be annoying eg. if `web.run()` we will get like 7 outputs?  I'm fine with reducing the print output in get_credentials.

Also, can we use log.info instead of print?

2022-03-29 18:35 UTC, lei-flex commented
os.environ["TIDY3D_USER"]
os.environ["TIDY3D_PASS"]

2022-03-29 18:38 UTC, lei-flex commented
when credential is verified, we can also set values back to env.
os.environ["TIDY3D_USER"]
os.environ["TIDY3D_PASS"]

also the current solution requested unnecessary calls for auth. It is fine for right now.
the correct way is check the response for each call, if 401 error, then retrieve the credential again for your refrence: 
def handle_response(func):
    def wrapper(*args, **kwargs):
        resp = func(*args, **kwargs)
        if resp.status_code == 401 and Config.auth_retry < 1:
            getEmailPasswdAuthKey()
            Config.auth_retry = Config.auth_retry + 1
            resp = func(*args, **kwargs)
        elif resp.status_code != 200:
            print(resp.content)
            resp.raise_for_status()
        try:
            Config.auth_retry = 0
            jsn = resp.json()['data']
        except Exception as e:
            print('Could not json decode response : {0}!'.format(resp.text))
            raise
        return jsn

    return wrapper

2022-03-30 18:18 UTC, tylerflex commented on tidy3d/web/auth.py
> +import logging
`from ..log import log`

2022-03-30 18:18 UTC, tylerflex commented on tidy3d/web/auth.py
> +        logging.debug("Using Tidy3D credentials from enviornment")
`log.debug`

2022-03-30 18:18 UTC, tylerflex commented on tidy3d/web/auth.py
> +        logging.info("Using Tidy3D credentials from stored file")
`log.info`

2022-03-30 18:18 UTC, tylerflex commented on tidy3d/web/auth.py
> +            logging.info("Error: Failed to log in with environment credentials.")
`log.info`

2022-03-30 18:18 UTC, tylerflex commented on tidy3d/web/auth.py
> +            logging.info("Error: Failed to log in with saved credentials.")
`log.info`

2022-03-30 18:18 UTC, tylerflex commented on tidy3d/web/auth.py
> +    attempts = 0
could also just do `for attempts in range(MAX_ATTEMPTS):` I think (or `for _ in range(MAX_ATTEMPTS)` if `attempts` is not used.

2022-03-30 18:18 UTC, tylerflex commented on tidy3d/web/auth.py
> +                logging.info("Error: Failed to store credentials.")
`log.info`

2022-03-30 18:18 UTC, tylerflex commented on tidy3d/web/auth.py
> +            logging.info("Error: Failed to log in with new username and password.")
`log.info`

2022-03-30 18:18 UTC, tylerflex commented on tidy3d/web/auth.py
> +                logging.info("Error: Failed to store credentials.")
`log.info`

2022-03-30 18:42 UTC, merged