add more log for auth when failed
flexcompute/tidy3d pull request #510
Opened 2022-09-20 20:07 UTC by lei-flex

add more log when login failed.

2022-09-22 07:42 UTC, tylerflex commented
@lei-flex just a heads up, for the front end tests to pass, need to 
```py
black . --line-length 100
```
to fix any formatting issues and then
```py
python lint.py
```
to run linter to ensure it's a clean lint / (10/10 score)

I just went ahead and fixed the issues but just a note for next time. Thanks!

2022-09-23 08:00 UTC, tylerflex requested changes

2022-09-23 08:00 UTC, tylerflex commented on tidy3d/web/auth.py
> +def __get_credential_from_env():
Could you add docstrings to these functions? just to describe what the logic is doing. For example:
```py
def _get_credential_from_env():
    """Try to get email and password from environment variables, if not encoded, encode it."""
```
or something similar, just to help us know what these functions should do, thanks

2022-09-26 23:53 UTC, momchil-flex commented
I did various tests, everything looks good. My only recommendation would be to bring back the `TIDY3D_ENV` variable as I mentioned on slack.

2022-09-27 01:57 UTC, lei-flex commented
> we should have the another ticket for TIDY3D_WEB_ENV. 
the purpose for this ticket is just to show more detail message during log and keep other logic no chang.e

2022-09-27 02:09 UTC, momchil-flex commented
Then fine by me to merge this.

2022-09-27 06:42 UTC, tylerflex approved these changes

2022-09-28 16:58 UTC, merged