Lower frequency bound and freezing seeds in fitter
flexcompute/tidy3d pull request #589
Opened 2022-12-01 19:14 UTC by weiliangjin2021

- Lower pole frequency bound for stable simulation when the dispersive medium is extended into PML.
- Freezing seeds in the fitter by default so that one obtains identical results when simply re-running the fitter.
- ignore k data option in `from_url` since sometimes the medium is in fact lossless but the URL provides data with small k at different wavelengths, e.g. https://refractiveindex.info/data_csv.php?datafile=data/glass/schott/N-BK7.yml

2022-12-02 09:47 UTC, tylerflex requested changes
Overall looks good, just a few comments about the API.

2022-12-02 09:47 UTC, tylerflex commented on tidy3d/plugins/dispersion/fit_web.py
> +    bound_lower_f: NonNegativeFloat = Field(
maybe `bound_f_lower` to be consistent with `bound_f`?

2022-12-02 09:47 UTC, tylerflex commented on tidy3d/plugins/dispersion/fit.py
> +        if has_k == 1 and ignore_k is False:
minor thing but
```py
if has_k == 1 and not ignore_k:
```

2022-12-02 09:47 UTC, tylerflex commented on tidy3d/plugins/dispersion/fit_web.py
> +        "frequency in the model :class:`.PoleResidue` (The default 'None' will trigger "
default is `0` so maybe we should change the description? also 'None' -> ``None`` for the description text.

2022-12-02 09:47 UTC, tylerflex commented on tidy3d/plugins/dispersion/fit_web.py
> +        True,
we could also consider making this an `int` called `random_seed` with default value of `0` or something. That way the user can change the seed if they want.

2022-12-02 18:17 UTC, weiliangjin2021 commented
> Overall looks good, just a few comments about the API.

All are good comments. Please see the latest commit.

2022-12-03 09:27 UTC, tylerflex requested changes
Thanks weiliang, looks good.
My only comment is that `random_seeds` should probably be singular: `random_seed`? since we only supply one? or else maybe I am misunderstanding the idea.

2022-12-04 17:25 UTC, weiliangjin2021 commented
> Thanks weiliang, looks good. My only comment is that `random_seeds` should probably be singular: `random_seed`? since we only supply one? or else maybe I am misunderstanding the idea.

That's right. It has been changed to singular.

2022-12-04 18:33 UTC, tylerflex approved these changes

2022-12-05 01:20 UTC, xin-flex approved these changes

2022-12-05 04:04 UTC, merged