Casey/2dmaterials
flexcompute/tidy3d pull request #733
Opened 2023-02-28 02:30 UTC by caseyflex

Todo:

- [ ] Add backend tests to validate simulation results (I just need to move these from my notebook)
- [ ] prohibit Simulation.medium from being a 2D medium
- [ ] validate that a 2d medium is added to a 2d geometry immediately when the structure is constructed
- [ ] autogrid for 2d materials

Plan for autogrid:
- Place a grid boundary at the 2d material
- Mesh the normal direction ignoring the 2d material
- Then mesh the in-plane directions using the volumetric equivalent

Limitations:
Autogrid will not support non-parallel 2d materials
Won't allow multiple 2d materials with separation smaller than the minimum grid size

2023-03-03 04:02 UTC, momchil-flex commented
Had only a first look so far but it's looking good! I closed the other two PRs, I think you've taken into account everything that was relevant.

2023-03-10 14:16 UTC, tylerflex reviewed
Hey @caseyflex since I've already reviewed it and am quite sick and low energy today, I was wondering whether you could summarize which parts of the code have been added / changed since the last iteration, so I can focus on that. Thanks and sorry for the inconvenience..

2023-03-10 14:22 UTC, caseyflex commented
> Hey @caseyflex since I've already reviewed it and am quite sick and low energy today, I was wondering whether you could summarize which parts of the code have been added / changed since the last iteration, so I can focus on that. Thanks and sorry for the inconvenience..

Hi @tylerflex, I hope you feel better soon and I think you could wait to review this after you are better. In my opinion, the only significant changes were in `tidy3d/components/simulation.py`, specifically in the `Simulation.grid` function. Some relevant tests were also added in `tests/test_components/test_grid_spec.py`. I think @momchil-flex  could also review these things though.

2023-03-10 15:02 UTC, tylerflex requested changes

2023-03-10 15:28 UTC, caseyflex commented on tidy3d/components/simulation.py
> +        _ = self.volumetric_structures
Momchil suggested this, it only creates overhead when 2d materials are present, so it should be OK. It validates e.g. that the 2d materials have homogeneous neighbors, as currently required

2023-03-13 18:07 UTC, tylerflex approved these changes

2023-03-14 13:27 UTC, tylerflex commented
@caseyflex I just tried to build the docs on this branch and got this error.
```py
Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/twhughes/.pyenv/versions/3.10.9/lib/python3.10/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/Users/twhughes/Documents/Flexcompute/tidy3d-docs/docs/source/conf.py", line 42, in <module>
    generate_doc.main()
  File "/Users/twhughes/Documents/Flexcompute/tidy3d-docs/docs/generate_doc.py", line 187, in main
    generate_material_library_doc()
  File "/Users/twhughes/Documents/Flexcompute/tidy3d-docs/docs/generate_doc.py", line 45, in generate_material_library_doc
    for abbr, mat in sorted(lib.items(), key=lambda item: item[1].name):  # iterate materials
  File "/Users/twhughes/Documents/Flexcompute/tidy3d-docs/docs/generate_doc.py", line 45, in <lambda>
    for abbr, mat in sorted(lib.items(), key=lambda item: item[1].name):  # iterate materials
AttributeError: type object 'Graphene' has no attribute 'name'
```
it might be that the changes are not yet compatible with generate_doc.py
Probably will need to work with @xin-flex to fix this.

2023-03-18 00:11 UTC, momchil-flex commented
I just rebased this branch w.r.t. latest pre/1.10.0 to fix the conflict with the now merged handling of the PEC material in gridding.

In the current version, I tried to follow if `Simulation._discretize_grid` is ever called with any grid that is different from `Simulation.grid`. I couldn't see how this would happen (which would mean that there's no need for `_discretize_grid`), but maybe I missed something. Do you know?

More generally as per the chat on slack with Tom it sounds like we should actually not do any extra auto gridding in the tangential directions. You may leave some code commented for the future though. I leave it up to you how to handle this.

The other thing left to wrap up is the documentation issue that Tyler pointed out above.

Then Tom (or someone) should update his graphene notebook to use autogrid and see what happens. And we should be ready for a merge!

2023-03-20 12:01 UTC, caseyflex commented
Simulation._discretize_grid and Simulation._volumetric_structures_grid can be used when you want to use a grid that is not the simulation grid. This was used when generating the simulation grid for 2d materials; an intermediate grid is needed to base the volumetric equivalents on, before the simulation grid is fully computed. These functions are no longer used in this way now that the in-plane autogrid code for 2d materials is commented out, however it would be good to leave them in case we decide to include this in-plane autogrid in the future.

2023-03-20 15:59 UTC, tomflexcompute approved these changes

2023-03-23 18:35 UTC, merged