Add get running task api
flexcompute/tidy3d pull request #859
Opened 2023-04-26 02:17 UTC by An-Li-magicloud

2023-04-26 12:48 UTC, tylerflex requested changes
Could you add a line in CHANGELOG.md under "Added"
```
- Add `SimulationTask.get_running_tasks()` to get a list of running tasks from the server.
```

@An-Li-magicloud is this finished or do you have more changes to add?

2023-04-26 12:48 UTC, tylerflex commented on tidy3d/web/simulation_task.py
> +        :class:`[.SimulationTask]`
let's do
```
List[:class:`.SimulationTask`]
```
or else it won't render properly in our docs.

2023-04-26 12:48 UTC, tylerflex commented on tidy3d/web/simulation_task.py
> +    def get_running_tasks(cls) -> [SimulationTask]:
our convention is to use
```py
List[SimulationTask]
```
with
```py
from typing import List
```

2023-04-26 12:48 UTC, tylerflex commented on tidy3d/web/simulation_task.py
> +        resp = http.get("tidy3d/py/tasks")
can we split this up a little to make it easier to read?
```py
if not resp:
    return []
return parse_obj_as(List[SimulationTask], resp)
```

2023-04-26 12:48 UTC, tylerflex commented on tidy3d/web/simulation_task.py
> +        """Get running tasks from the server.
```
"Get a list of running tasks from the server"
```

just to be a little more specific that it's a list

2023-04-27 02:30 UTC, An-Li-magicloud commented
> Could you add a line in CHANGELOG.md under "Added"
> 
> ```
> - Add `SimulationTask.get_running_tasks()` to get a list of running tasks from the server.
> ```
> 
> @An-Li-magicloud is this finished or do you have more changes to add?

This is part of https://flow360.atlassian.net/browse/SCEM-2452 . 

It could help user to get running tasks if connection issue or python kernel gone.

Let's merge this and discuss more about how to improve monitor in the ticket.

2023-05-03 20:08 UTC, tylerflex approved these changes

2023-05-04 01:26 UTC, merged